### ISSUE TITLE
Cannot Connect Windows Beats

### ISSUE THREAD

**Issue by fahad-1406** [Graylog2/docker-compose#18]
The default docker-compose.yml is missing port 5044 to allow for winlog beat to connect, update the ports section like below please:
     ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # Beats
      - 5044:5044

**Comment by bernd** [comment]
@fahad-1406 The [open-core/docker-compose.yml](https://github.com/Graylog2/docker-compose/blob/02bc378a2b0d9a1d47485464d463803df8104d7f/open-core/docker-compose.yml#L43) and [enterprise/docker-compose.yml](https://github.com/Graylog2/docker-compose/blob/02bc378a2b0d9a1d47485464d463803df8104d7f/enterprise/docker-compose.yml#L44) files both contain a port mapping for `5044`. We didn't include it in the cluster setup because of potential port conflicts.

These Docker Compose files mainly serve as examples. Users can modify the files according to their needs.
